"""add_queue_invites

Revision ID: 412b94f26771
Revises: 69ab48e8b4e4
Create Date: 2026-02-21 22:13:00.875670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '412b94f26771'
down_revision: Union[str, Sequence[str], None] = '69ab48e8b4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=6), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('queue_id', 'user_id', name='uq_queue_invite_user')
    )
    with op.batch_alter_table('queue_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queue_invites_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_invites_queue_id'), ['queue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_invites_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queue_invites_user_id'))
        batch_op.drop_index(batch_op.f('ix_queue_invites_queue_id'))
        batch_op.drop_index(batch_op.f('ix_queue_invites_id'))

    op.drop_table('queue_invites')
    # ### end Alembic commands ###
