"""add_on_behalf_of_to_tickets_and_comments

Revision ID: 82e2293d1786
Revises: e7da6b1f5f49
Create Date: 2026-02-21 01:20:07.358129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '82e2293d1786'
down_revision: Union[str, Sequence[str], None] = 'e7da6b1f5f49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('on_behalf_of_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_comments_on_behalf_of_id', 'users', ['on_behalf_of_id'], ['id'])

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('on_behalf_of_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tickets_on_behalf_of_id', 'users', ['on_behalf_of_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tickets_on_behalf_of_id', type_='foreignkey')
        batch_op.drop_column('on_behalf_of_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_on_behalf_of_id', type_='foreignkey')
        batch_op.drop_column('on_behalf_of_id')

    # ### end Alembic commands ###
