"""add_notification_tables

Revision ID: a3abdaa5eb90
Revises: b265b6b652b6
Create Date: 2026-02-13 20:34:14.252098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3abdaa5eb90'
down_revision: Union[str, Sequence[str], None] = 'b265b6b652b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'token', name='uq_user_token')
    )
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('user_queue_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('pageable_start', sa.String(length=5), nullable=False),
    sa.Column('pageable_end', sa.String(length=5), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('sev1_off_hours_opt_out', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'queue_id', name='uq_user_queue_settings')
    )
    with op.batch_alter_table('user_queue_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_queue_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_queue_settings_queue_id'), ['queue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_queue_settings_user_id'), ['user_id'], unique=False)

    op.create_table('escalation_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('original_priority', sa.Enum('SEV1', 'SEV2', 'SEV3', 'SEV4', name='ticketpriority'), nullable=False),
    sa.Column('last_escalation_at', sa.DateTime(), nullable=True),
    sa.Column('escalation_count', sa.Integer(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    with op.batch_alter_table('escalation_tracking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escalation_tracking_id'), ['id'], unique=False)

    op.create_table('page_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('last_page_sent_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    with op.batch_alter_table('page_tracking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_tracking_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_tracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_tracking_id'))

    op.drop_table('page_tracking')
    with op.batch_alter_table('escalation_tracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escalation_tracking_id'))

    op.drop_table('escalation_tracking')
    with op.batch_alter_table('user_queue_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_queue_settings_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_queue_settings_queue_id'))
        batch_op.drop_index(batch_op.f('ix_user_queue_settings_id'))

    op.drop_table('user_queue_settings')
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_device_tokens_id'))

    op.drop_table('device_tokens')
    # ### end Alembic commands ###
