name: Auto-merge

on:
  pull_request:
    types: [opened]

jobs:
  auto-merge:
    if: github.actor == 'rosalogia'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - run: gh pr merge ${{ github.event.number }} --auto --squash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
